import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/lib/providers/theme-provider';
import QueryProvider from '@/lib/providers/query-client';
import { SFPRO } from '../assets/fonts/SFPRO';
import Hydration from '@/components/hydration';

const sfpro = SFPRO;

export const metadata: Metadata = {
  title: 'Rasmus Elmersson',
  description: 'Generated by create next app'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={sfpro.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            storageKey="macos-theme"
          >
            <Hydration />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </QueryProvider>
  );
}
