import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import Wallpaper from "@/components/wallpaper";
import { Navbar } from "@/components/navbar";
import { Boot } from "@/components/boot";
import { useSystem } from "@/hooks/useSystem";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rasmus Elmersson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="macos-theme"
        >
          <Boot />
          <Navbar />
          {children}
          <Wallpaper />
        </ThemeProvider>
      </body>
    </html>
  );
}
